# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7


matrix:
  fast_finish: true
  include:
    - name: flake8-test
      python: 3.7
      install: pip install -U flake8
      script: flake8 percy tests

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

